//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowColours.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public string Name { get; set; }
        public string RGB { get; set; }
        public string Web { get; set; }
        public string HSL { get; set; }
        public string CMYK { get; set; }
    }
}
